[build]
  publish = "public"
  command = "npm run build"

[build.ignore]
  # Only build if there are changes in the PROJECT-1 directory
  command = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF -- PROJECT-1"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
